[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "first-github-scraper"
version = "1.0.0"
description = "An introduction to free, automated web scraping with GitHub’s powerful Actions framework"
readme = "README.md"
requires-python = "==3.13.*"
license = "MIT"
dependencies = [
    "sphinx",
    "sphinx-autobuild",
    "sphinx-multitoc-numbering",
    "myst-parser",
    "sphinx-palewire-theme>=0.1.10",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
]

[dependency-groups]
dev = [
    "jupyterlab",
    "requests",
    "bs4",
]

[tool.setuptools]
packages = []
